server:
  port: 8080
spring:
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    test-while-idle: true                       #验证连接的有效性
    test-on-borrow: true                        #获取连接时候验证
    validation-query: select 1 from dual        #查询虚拟表dual
    time-between-eviction-runs-millis: 300000   #空闲连接回收的时间间隔,设置5分钟
    min-evictable-idle-time-millis: 1800000     #连接池空闲连接的有效时间 ,设置30分钟
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true